apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devnopes.name" . }}
  labels:
    {{- include "devnopes.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "devnopes.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "devnopes.name" . }}
    namespace: {{ .Values.job.namespace }}
