apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-diagnostics.name" . }}
  namespace: {{ .Values.job.namespace }}
  labels:
    {{- include "k8s-diagnostics.labels" . | nindent 4 }}
