name: Sysdig - Build, scan, push and upload sarif report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 1 * * 5'

permissions:
  contents: read

jobs:
  build:
    if: ${{ secrets.SYSDIG_SECURE_TOKEN != '' }}
    permissions:
      checks: write
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
      - name: Sysdig Secure Inline Scan
        id: scan
        uses: sysdiglabs/scan-action@768d7626a14897e0948ea89c8437dd46a814b163
        with:
          image-tag: ${{ github.repository }}:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: https://us2.app.sysdig.com
          dockerfile-path: ./Dockerfile
          input-type: docker-daemon
          ignore-failed-scan: true
          run-as-user: root
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}
